"""Shared plotting style for figures used by non_BTD.md.

The report figures are generated by scripts kept in the repository so the
presentation can be reproduced from source.  Text labels are written as LaTeX
strings and rendered with Matplotlib's TeX backend when available.
"""

from __future__ import annotations

import shutil

import matplotlib as mpl


REPORT_COLORS = {
    "blue": "#1f77b4",
    "orange": "#ff7f0e",
    "green": "#2ca02c",
    "red": "#d62728",
    "gray": "#6b7280",
    "navy": "#102a43",
}


def use_report_style(use_tex: bool = True) -> None:
    tex_available = shutil.which("latex") is not None
    mpl.rcParams.update(
        {
            "figure.dpi": 150,
            "savefig.dpi": 220,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.03,
            "axes.linewidth": 1.1,
            "axes.labelsize": 14,
            "axes.titlesize": 15,
            "axes.grid": True,
            "grid.alpha": 0.25,
            "grid.linewidth": 0.7,
            "legend.frameon": True,
            "legend.fontsize": 11,
            "xtick.labelsize": 12,
            "ytick.labelsize": 12,
            "lines.linewidth": 1.8,
            "font.family": "serif",
            "mathtext.fontset": "cm",
            "text.usetex": bool(use_tex and tex_available),
            "text.latex.preamble": r"\usepackage{amsmath}",
        }
    )
